from typing import Dict


SUPPORTED_LANGUAGES: Dict[str, str] = {
    "ar": "Arabic",
    "bg": "Bulgarian",
    "cs": "Czech",
    "da": "Danish",
    "de": "German",
    "el": "Greek",
    "en": "English",
    "fi": "Finnish",
    "fr": "French",
    "hu": "Hungarian",
    "id": "Indonesian",
    "it": "Italian",
    "ja": "Japanese",
    "ko": "Korean",
    "no": "Norwegian",
    "nl": "Dutch",
    "pl": "Polish",
    "pt": "Portuguese",
    "ro": "Romanian",
    "ru": "Russian",
    "sk": "Slovak",
    "sv": "Swedish",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "vi": "Vietnamese",
    "zh": "Chinese"
}


SUPPORTED_LANGUAGES_DEEPL: Dict[str, str] = {
    "ar": "AR",
    "bg": "BG",
    "cs": "CS",
    "da": "DA",
    "de": "DE",
    "el": "EL",
    "en": "EN",
    "fi": "FI",
    "fr": "FR",
    "hu": "HU",
    "id": "ID",
    "it": "IT",
    "ja": "JA",
    "ko": "KO",
    "no": "NB",
    "nl": "NL",
    "pl": "PL",
    "pt": "PT-PT",
    "ro": "RO",
    "ru": "RU",
    "sk": "SK",
    "sv": "SV",
    "tr": "TR",
    "uk": "UK",
    "vi": "VI",
    "zh": "ZH",
}


SUPPORTED_LANGUAGES_AZURE: Dict[str, str] = {
    "ar": "ar",
    "bg": "bg",
    "cs": "cs",
    "da": "da",
    "de": "de",
    "el": "el",
    "en": "en",
    "fi": "fi",
    "fr": "fr",
    "hu": "hu",
    "id": "id",
    "it": "it",
    "ja": "ja",
    "ko": "ko",
    "no": "nb",
    "nl": "nl",
    "pl": "pl",
    "pt": "pt",
    "ro": "ro",
    "ru": "ru",
    "sk": "sk",
    "sv": "sv",
    "tr": "tr",
    "uk": "uk",
    "vi": "vi",
    "zh": "zh-Hans",
}
